### ISSUE TITLE
Header : submenu list was not aligned left as per psd design.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#10]
![image](https://cloud.githubusercontent.com/assets/12791909/13135650/b99b9db6-d64d-11e5-8084-4097b95d22db.png)

**Comment by mahender-sowedane** [comment]
Not fixed

![2016-03-02_1708-banner01](https://cloud.githubusercontent.com/assets/13309730/13483595/aec5f41c-e11b-11e5-9af1-d82ef809ec95.png)

**Comment by mahender-sowedane** [comment]
Not fixed.
![2016-03-29_1046](https://cloud.githubusercontent.com/assets/13309730/14098650/c376053e-f59b-11e5-8598-878f567b80d6.png)
