### ISSUE TITLE
Inner Banner : Inner banner images are too streatch

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Ergoline-Furniture#106]

**Comment by mahender-sowedane** [comment]
![2016-03-28_1549](https://cloud.githubusercontent.com/assets/13309730/14076174/0eb1f73c-f4fd-11e5-880b-ac68d83843e3.png)

**Comment by ravititan** [comment]
@mahender-sowedane : Need to upload the image minimum size of  1920w x 147h , to show full width. If the image is small in size it will be in the center/
