### ISSUE TITLE
Banner section : Navigation icons are not displaying on devices portrait mode

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Ergoline-Furniture#107]
Devices : IPad, IPad(mini), Samsung E7, ITouch

![ipad](https://cloud.githubusercontent.com/assets/13309730/14100981/dfc1b73e-f5ae-11e5-962a-c4ab7ba48aa7.png)
avi

**Comment by ravititan** [comment]
For consistency of the banner title and buttons i have removed the nav dots.
