### ISSUE TITLE
Homepage : Map marker has incorrect font used. Font As per design should be Lato regular.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#22]
![image](https://cloud.githubusercontent.com/assets/12791909/13242943/09df1a7e-da35-11e5-99b1-e8563eebfccb.png)

**Comment by ravititan** [comment]
I have checked the PSD and the heading font is Arial not Lato , Lato Font is for the description under that.

**Comment by mahender-sowedane** [comment]
Not fixed, Re-check psd once again.
