### ISSUE TITLE
Homepage : ordered and unordered list font element is not the same with homepage font elements.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#24]
![image](https://cloud.githubusercontent.com/assets/12791909/13243036/de6d545e-da35-11e5-9f08-e91915e08dda.png)

**Comment by mahender-sowedane** [comment]
Not fixed affected all single pages

![2016-03-02_1747-content-news_single](https://cloud.githubusercontent.com/assets/13309730/13483722/0c81f2e4-e11d-11e5-93d9-479144f90c70.png)
