### ISSUE TITLE
General : Header 3-6 font element is not consistent with header 2 and 1

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#26]
![image](https://cloud.githubusercontent.com/assets/12791909/13243366/3b4425ec-da39-11e5-90bf-f8f8786889dd.png)

**Comment by mahender-sowedane** [comment]
not fixed
It should be follow titan standards.

![2016-03-08_1250-issue](https://cloud.githubusercontent.com/assets/13309730/13594726/5a068594-e52c-11e5-9950-800bfd7895e9.png)

**Comment by mahender-sowedane** [comment]
Not fixed
