### ISSUE TITLE
About Us : Inner banner image acf not reflected on the front end. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#27]
![image](https://cloud.githubusercontent.com/assets/12791909/13243482/18cbc334-da3a-11e5-88c1-7e879616c6e7.png)

**Comment by mahender-sowedane** [comment]
Not fixed, affected on all single pages

![innerbannr](https://cloud.githubusercontent.com/assets/13309730/13484320/ac7d4bb8-e122-11e5-882e-02897ae5b4c3.png)

**Comment by ravititan** [comment]
@mahender-sowedane : We have removed the acf field for inner banner images.
