### ISSUE TITLE
General : Incorrect font used for breadcrumbs. Font should be Arial

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#29]
![image](https://cloud.githubusercontent.com/assets/12791909/13243715/f7dd8160-da3b-11e5-9c33-fc01727d2f3e.png)

**Comment by mahender-sowedane** [comment]
Not fixed, breadcrumbs are missing previously working fine.

![2016-03-03_0857-test](https://cloud.githubusercontent.com/assets/13309730/13483836/2651fde4-e11e-11e5-9478-2081115167e5.png)
