### ISSUE TITLE
Our Range - Inner banner ACF was found in adding product category section

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#31]
![image](https://cloud.githubusercontent.com/assets/12791909/13243995/f2ee7cb6-da3d-11e5-8daa-9bf691317faa.png)

**Comment by ravititan** [comment]
This is because we have Inner Banner in Desing(PSD) for Categories.

**Comment by mahender-sowedane** [comment]
Not fixed, Refer the psd and fix it properly
thanks!
