### ISSUE TITLE
Our Range - Single Page : Product image size not the same with the design

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#34]
![image](https://cloud.githubusercontent.com/assets/12791909/13272319/256a3390-dad6-11e5-85e1-061be32437c0.png)

**Comment by mahender-sowedane** [comment]
Still not implemented as per design
Also accordion arrow's should be vertically center align.

![untitled-1-productss](https://cloud.githubusercontent.com/assets/13309730/13595445/6d7efbec-e531-11e5-8078-50746f693f75.png)
