### ISSUE TITLE
Our Range - Single Page : ordered and unordered list font font elements are inconsistent with the other content.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#40]
![image](https://cloud.githubusercontent.com/assets/12791909/13272575/2d6ac120-dad8-11e5-83b6-7329a3833eb5.png)

**Comment by mahender-sowedane** [comment]
![2016-03-02_1747-content-news_single](https://cloud.githubusercontent.com/assets/13309730/13593690/a8b10ca4-e523-11e5-9577-278aba35efb4.png)
