### ISSUE TITLE
Our Range-Single Page : Overlapping of product specification fields icon and value 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#44]
![image](https://cloud.githubusercontent.com/assets/12791909/13272961/f801dde0-dada-11e5-92e8-0cd2f4139b1b.png)

**Comment by mahender-sowedane** [comment]
not fixed, still overlapping text.

![2016-03-08_1857-issue01](https://cloud.githubusercontent.com/assets/13309730/13603008/37d09328-e560-11e5-912d-954638ef83dc.png)
