### ISSUE TITLE
Our Range : Broken category images grid layout.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#46]
![image](https://cloud.githubusercontent.com/assets/12791909/13273212/cef615d6-dadc-11e5-8ed2-0a9ee349ce8f.png)

**Comment by mahender-sowedane** [comment]
Still not fixed properly

![issue46](https://cloud.githubusercontent.com/assets/13309730/13591937/7cf782ba-e513-11e5-86cc-3a2695deedea.png)
