### ISSUE TITLE
Our Range : Long category title overflow with category image

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#47]
Ipad, iTouch

![image](https://cloud.githubusercontent.com/assets/12791909/13273261/1fb45190-dadd-11e5-9385-f3ec6a6408ec.png)

**Comment by mahender-sowedane** [comment]
Not fixed, affected on small devices

![2016-03-03_1114-360](https://cloud.githubusercontent.com/assets/13309730/13485781/2e8616fe-e131-11e5-8f87-a5d00e19b197.png)

**Comment by mahender-sowedane** [comment]
Still issue is not fixed.

![2016-03-29_1027](https://cloud.githubusercontent.com/assets/13309730/14098399/fb20dd5e-f598-11e5-83a0-9c8493cc75da.png)
