### ISSUE TITLE
Our Range : Product list - incorrect font element used. Font should be Myriad Pro and size should be 17px

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#48]
![image](https://cloud.githubusercontent.com/assets/12791909/13273348/b3da7610-dadd-11e5-90da-94ef40e1efdb.png)

**Comment by ravititan** [comment]
I have checked the PSD and the font is Arial, Attached is a screenshot.
![subcategory-font](https://cloud.githubusercontent.com/assets/13450891/13317956/0ac9f74c-dbde-11e5-8d53-5a463e072726.jpg)
