### ISSUE TITLE
News : Featured image size not the same with the design

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#49]
![image](https://cloud.githubusercontent.com/assets/12791909/13274074/8e4f91a4-dae3-11e5-9bb5-39d7dcd4d923.png)

**Comment by mahender-sowedane** [comment]
Not fixed

![2016-03-03_1109](https://cloud.githubusercontent.com/assets/13309730/13485718/96654d4a-e130-11e5-9041-6ad5ee66ab00.png)
