### ISSUE TITLE
News - pagination were displayed aligned with the news featured image. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#51]
![image](https://cloud.githubusercontent.com/assets/12791909/13274249/e1ba0bfc-dae4-11e5-85ad-3f4ecb4ecfbb.png)

**Comment by mahender-sowedane** [comment]
Still not aligned properly and Inconsistent gap. It should be as per design

![2016-03-03_1049-678](https://cloud.githubusercontent.com/assets/13309730/13485474/2472121a-e12e-11e5-999d-fd7cfe54bccc.png)

**Comment by mahender-sowedane** [comment]
Still issue is not fixed
