### ISSUE TITLE
Contact Us : Broken fields alignment occurs after adding valid email only and then submit

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#55]
![image](https://cloud.githubusercontent.com/assets/12791909/13274696/3cd88574-dae8-11e5-8f54-ffc22fb57cb6.png)

**Comment by mahender-sowedane** [comment]
Not fixed, lacking of padding for inputted text & fields are clipped on browser re-flow.

![2016-03-03_1040](https://cloud.githubusercontent.com/assets/13309730/13485330/a9cffe92-e12c-11e5-84c9-fe8bc16bf41f.png)
