### ISSUE TITLE
Footer : Titan logo should be displayed in the footer. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#63]
![image](https://cloud.githubusercontent.com/assets/12791909/13275194/441ed694-daed-11e5-9964-2c3b596459b7.png)

**Comment by ravititan** [comment]
It is mentioned in scope not to use Titan logo
![seo-footer](https://cloud.githubusercontent.com/assets/13450891/13314864/63cdacb4-dbcd-11e5-926e-22ffda6be4fc.jpg)
