### ISSUE TITLE
Header : google+ icon goes down via Microsoft edge browser.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#65]
Browser : Microsoft Edge

![image](https://cloud.githubusercontent.com/assets/12791909/13275263/0d06517c-daee-11e5-9dea-91a66832c52e.png)

**Comment by mahender-sowedane** [comment]
Not fixed

![2016-03-05_1317-ie-issue65](https://cloud.githubusercontent.com/assets/13309730/13592092/ebccc0b4-e514-11e5-84fa-8ba273472380.png)
