### ISSUE TITLE
Mobile: Our Range - sub category list featured image not aligned via portrait mode

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#68]
![image](https://cloud.githubusercontent.com/assets/12791909/13276660/94e1d112-dafc-11e5-9607-3fb6495fb736.png)

**Comment by mahender-sowedane** [comment]
Still alignment is broken

![2016-03-08_1213-996](https://cloud.githubusercontent.com/assets/13309730/13594073/5f773bea-e527-11e5-801c-6170247005f9.png)
