### ISSUE TITLE
Mobile : Our Range - product list featured image doesn't have space between them.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#69]
![image](https://cloud.githubusercontent.com/assets/12791909/13276704/242d1994-dafd-11e5-8a9d-448812779770.png)

**Comment by mahender-sowedane** [comment]
Not fixed

![2016-03-05_1304-issue69](https://cloud.githubusercontent.com/assets/13309730/13592138/5fc12e42-e515-11e5-97ad-572b5cf570f1.png)
