### ISSUE TITLE
Mobile: Our Range product featured images displayed a broken image

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#70]
Device : Ipad Air

![image](https://cloud.githubusercontent.com/assets/12791909/13276765/8d9637bc-dafd-11e5-881c-1e0f0c64c5ab.png)

**Comment by ravititan** [comment]
I have tested in on Ipad Air and its working fine.

**Comment by mahender-sowedane** [comment]
Broken alignment & overlapped each other if title is too long on reflow.

![2016-03-08_1224-issue70](https://cloud.githubusercontent.com/assets/13309730/13594265/ea18c29a-e528-11e5-90c6-fafbd8f01be9.png)

**Comment by mahender-sowedane** [comment]
Still issue is not fixed
