### ISSUE TITLE
Mobile: Our Range - Product gallery images displays an empty space

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#71]
Ipad Air - portrait

![image](https://cloud.githubusercontent.com/assets/12791909/13276794/d34e83b8-dafd-11e5-9755-f985b5445f76.png)

**Comment by mahender-sowedane** [comment]
Not fixed properly
Accordion arrow icon's are overlapping with images on small devices.

![2016-03-05_1258-445](https://cloud.githubusercontent.com/assets/13309730/13592229/45071f98-e516-11e5-9732-4543753d19c9.png)
