### ISSUE TITLE
Mobile: Lead-ins featured image is stretch.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#76]
iTouch

![image](https://cloud.githubusercontent.com/assets/12791909/13306449/b84ecc48-db9e-11e5-96db-09437b0fa9d6.png)

**Comment by mahender-sowedane** [comment]
Still not fixed

![2016-03-08_1217-imagestretch](https://cloud.githubusercontent.com/assets/13309730/13594125/cd849da8-e527-11e5-8145-ce75e2776ccf.png)
