### ISSUE TITLE
Mobile : Field boxes has orange outline. Visible on all gravity forms and search box

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#78]
E7

![image](https://cloud.githubusercontent.com/assets/12791909/13306782/847fd576-dba1-11e5-9c1d-b97e6d205866.png)

**Comment by mahender-sowedane** [comment]
Not fixed

![screenshot_2016-03-05-12-48-48](https://cloud.githubusercontent.com/assets/13309730/13592343/537cf128-e517-11e5-8cbb-cdf95a2088df.png)
