### ISSUE TITLE
Header : submenu was not properly styled.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Ergoline-Furniture#8]
![image](https://cloud.githubusercontent.com/assets/12791909/13135307/6671a624-d64a-11e5-8d36-74d9def49dce.png)

**Comment by mahender-sowedane** [comment]
not fixed.
Not styled and lacking of padding.
![2016-03-03_0834-ss](https://cloud.githubusercontent.com/assets/13309730/13483525/17a5dfe8-e11b-11e5-944d-309c2fe04d95.png)
