### ISSUE TITLE
Our Range-Single Page-Mobile: Custom post content does not occupies the whole mobile width.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Ergoline-Furniture#90]
![2016-03-08_1457 widthtext](https://cloud.githubusercontent.com/assets/13309730/13597377/43f3b8aa-e53e-11e5-8106-d8f2db36b34c.png)

**Comment by ravititan** [comment]
@mahender-sowedane : after 768px it is full width, and we have a product specification section beside that. So after 768px the product specification will go down and the content will occupy the fullwidth.
